version: '3.9'

services:
  kursor-postgres:
    image: postgres:latest
    container_name: kursor-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
  kursor-redis:
    image: redis:latest
    container_name: kursor-redis
    restart: always
    ports:
      - 6379:6379


volumes:
  postgres-volume:
    external: false
