version: '3.9'

services:
  gitroom-postgres:
    image: postgres:latest
    container_name: gitroom-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
  gitroom-redis:
    image: redis:latest
    container_name: gitroom-redis
    restart: always
    ports:
      - 6379:6379


volumes:
  postgres-volume:
    external: false
