version: '3.9'

services:
  kursor-postgres:
    image: postgres:latest
    container_name: kursor-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
  kursor-redis:
    image: redis:latest
    container_name: kursor-redis
    restart: always
    ports:
      - 6379:6379
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    ports:
      - '4200:4200'
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env.dev

volumes:
  postgres-volume:
    external: false
